name: Buat Todo Otomatis

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  buat-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Buat Todo issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Kerjakan fitur absensi harian"
          content-filepath: .github/todo/absensi.md
          labels: todo
